services:
  viewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: affinitydocker
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    #volumes:
    #   - config_persist:/config
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - "/dev/dri:/dev/dri"
    group_add:
      - video

#volumes:
#  config_persist:
