name: Build and Push affinity-wine to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile.wine
      - .github/workflows/build-wine.yml
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.wine
          push: true
          tags: >
            ghcr.io/${{ github.repository }}/wine:latest,
            ghcr.io/${{ github.repository }}/wine:elementalwarrior
          cache-from: type=gha
          cache-to: type=gha,mode=max
